export default {
  ru: {
    showMap: "Показать карту",
    showList: "Показать списком",
    call: "Позвонить",
    send: "Написать",
    phone: "Телефон:",
    category: "Категория транспорта:",
    name: "Имя:",
    switchLanguage: "На Английский",
    filter: "Фильтр",
    bus: "Пассажирский",
    lorry: "Грузовой",
    special: "Спецтранспорт",
  },
  en: {
    showMap: "Show map",
    showList: "Show list",
    call: "Call",
    send: "Write",
    phone: "Phone:",
    category: "Transport сategory:",
    name: "Name:",
    switchLanguage: "To Russian",
    filter: "Filter",
    bus: "Bus",
    lorry: "Lorry",
    special: "Special",
  },
};
